//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fyptest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card
    {
        public string cardNo { get; set; }
        public int ccv { get; set; }
        public string expireDate { get; set; }
    }
}
