//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fyptest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chat
    {
        public int conversation_id { get; set; }
        public string sender_id { get; set; }
        public string receiver_id { get; set; }
        public string message { get; set; }
        public string message_status { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string group_name { get; set; }
        public string is_media { get; set; }
    
        public virtual ChatConnection ChatConnection { get; set; }
    }
}
