//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fyptest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seeker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Seeker()
        {
            this.ChatConnections = new HashSet<ChatConnection>();
            this.Requests = new HashSet<Request>();
        }
    
        public string email { get; set; }
        public string name { get; set; }
        public string password { get; set; }
        public string phone { get; set; }
        public string profileImage { get; set; }
        public int status { get; set; }
        public Nullable<int> loginCount { get; set; }
        public string token { get; set; }
        public Nullable<System.DateTime> tokenExpire { get; set; }
        public string connectionGroup { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChatConnection> ChatConnections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request> Requests { get; set; }
    }
}
