//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fyptest
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatConnection
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChatConnection()
        {
            this.Chats = new HashSet<Chat>();
        }
    
        public string group_name { get; set; }
        public int connection_id { get; set; }
        public string seeker_email { get; set; }
        public string provider_email { get; set; }
        public Nullable<System.DateTime> first_chat_datetime { get; set; }
        public Nullable<System.DateTime> last_chat_datetime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chat> Chats { get; set; }
        public virtual Provider Provider { get; set; }
        public virtual Seeker Seeker { get; set; }
    }
}
